name: Update Data

on:
  schedule:
    - cron:   # Run at 9:00 AM, 12:00 PM, and 5:00 PM (Mon-Fri)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.2  # Adjust as needed

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: '121.0.6167.139'  # Specify the correct version

      - name: Run Python script
        run: python scripts/update_data.py
        
      - name: Set Git user email and name
        run: |
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
        
      - name: Stage changes
        run: git add .
        
      - name: Commit changes
        run: |
          git commit -m "Update data" || echo "No changes to commit"
        
      - name: Pull prior to push
        run:  |
          git pull

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}